version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: mohammed_nizam
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: mohammed_nizam_db
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env 

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mohammed_nizam_db
      MYSQL_USER: mohammed_nizam
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: mohammed_nizam
      PMA_PASSWORD: ${PMA_PASSWORD}
    env_file:
      - .env   


volumes:
  wordpress:
  db:



